[colors.primary]
background = "#000000"
foreground = "#c7c7c7"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
dynamic_padding = false
dynamic_title = true
